### ISSUE TITLE
Dockerize this Server

### ISSUE THREAD

**Issue by tarunnsingh** [tarunnsingh/morph-server#12]
**Is your feature request related to a problem? Please describe.**
This is with reference to [this issue on the client repo](https://github.com/tarunnsingh/morph-client/issues/3). It would be better to dockerize this server, so that it can be deployed which would be a cake walk. Currently this Flask app shows error while deploying to HEROKU etc. As this uses CMake, DLib, OpenCV etc. which are often known for their compatibility issues.

**Describe the solution you'd like**
Create a Docker File, which when built EXPOSES a port to the API Endpoints.

**Describe alternatives you've considered**
I have tried this but while installing SYS REQ, CMake Fails giving error that Boost was not found.
```Dockerfile
FROM python:3.6.0

RUN python -m pip install pip==9.0.1

RUN apt-get update && apt-get install libboost-all-dev

WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
EXPOSE 5000

ENTRYPOINT [ "python" ]
CMD [ "app.py" ]
```

**Additional context**
This Server uses `python 3.6.0` and `pip 9.0.1`.

**Comment by jabhishek87** [comment]
IS it available i can take this? can somebody assign it to me

**Comment by tarunnsingh** [comment]
Yes @jabhishek87 it is available

**Comment by jabhishek87** [comment]
can we close this pr ?

**Comment by jabhishek87** [comment]
do we need anything else here?, can we close this issue
