### ISSUE TITLE
Add a Database for Storing Images.

### ISSUE THREAD

**Issue by tarunnsingh** [tarunnsingh/morph-server#3]
![image](https://user-images.githubusercontent.com/31896659/94581636-ed08e600-0298-11eb-8564-95dc2f1bc022.png)

Suggestion: **Can Use FLASK-SQL-Alchemy**  
Currently the Server saves all the images and morphs in a local storage of the server folder itself. Implementing a database would help in optimizing speeds of different operations and also enable the path to create more feature like saving morphs for different users etc.

**Comment by mehta-raghav** [comment]
@tarunnsingh Would doing it in sqlite suffice or would you like to suggest any other RDBMS?

**Comment by tarunnsingh** [comment]
Since most people have a good hand at Flask+SQL, I asked for the same, otherwise it's completely upto you. You can even use non-relational DBs.

**Comment by mehta-raghav** [comment]
Okay then, I'll implement it with sqlite. You can assign this to me.

**Comment by tarunnsingh** [comment]
Alright
